name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Builds the steamboat whitelabel versions
      run: |
        git config --global user.email "line72@line72.net"
        git config --global user.name "Marcus Dillavou"
        ./build.sh
